# Generated by Django 5.1.1 on 2024-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("hair", "Hair Care"),
                    ("skin", "Skin Care"),
                    ("body", "Body Care"),
                ],
                default="hair",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shipping_options",
            field=models.TextField(default="Standard shipping"),
        ),
    ]
